---
# initialize environment and create the necessary directories
- name: "Initialize Site Directory Env"
  file: path=/var/www/html/360emed-api state=directory group=webteam owner=apptadmin
  sudo: true
  sudo_user: root

- name: "Deploy Site"
  local_action: git repo=https://github.com/360Emed/360emed-api.git dest="/var/tmp/360emed-api" version="master" force=yes
  become: false
  run_once: true

- name: "Composer install"
  local_action: command php composer.phar install chdir=/var/tmp/360emed-api
  become: false
  run_once: true

- name: "delete the git folder, it's not needed for app to run"
  local_action: command rm -rf .git chdir=/var/tmp/360emed-api
  become: false
  run_once: true

# Setup Configuration File
- synchronize: src=/var/tmp/360emed-api dest="/var/www/html/"
  become: false

- name: "Change log dir permission"
  file: path=/var/www/html/360emed-api/var/logs state=directory group=webteam owner=apptadmin mode=0777
  sudo: true
  sudo_user: root

- name: "Change cache dir permission"
  file: path=/var/www/html/360emed-api/var/cache state=directory group=webteam owner=apptadmin mode=0777
  sudo: true
  sudo_user: root
